### ISSUE TITLE
make some changes

### ISSUE THREAD

**Issue by kakamband** [suconghou/ustream-heroku#1]
Hi suconghou,
at the first special thanks for your special gits :)
please if it's possible make this changes for best performance :
1-make limit for embed only on one domain set in env values on heroku dyno , for exam embed link only work on x.gg domain
2-make auto choose quality by buffer rate bandwidth & add many range of quality simple like 2k,4k or 8k can choosable on player
3-make clone of auto translate subtitle feture exist in official youtube
4-changes on heroku git for read all assets locally instead of read from addresses like assets.sukonghou.cn . because of asian distance to heroku dyno is so faar.
5-make rss feed for search results
waiting for your response
finest regards

**Comment by kakamband** [comment]
hi suconghou,
I did not receive a response to the result of the last message sent to you, is there a problem?

**Comment by suconghou** [comment]
no plans to support these features
